apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskflow-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "taskflow-ui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
