apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-ui
  namespace: taskflow
  labels:
    app: taskflow-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: taskflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskflow-ui
                port:
                  number: 80
