apiVersion: v1
kind: Service
metadata:
  name: taskflow-ui
  namespace: taskflow
  labels:
    app: taskflow-ui
    app.kubernetes.io/name: taskflow-ui
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: taskflow-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
